is-up/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :equals
  resources :estados
  get 'users/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'welcome#index'
  resources :comentarios
  resources :gustos
  resources :locals
  resources :comunas
  resources :usuarios
  resources :users
  get 'welcome/index'
  root 'welcome#index'
  get 'users/index2', to: 'users#index2'
  get 'welcome/index', to: 'welcome#index'
  get 'usuarios/new', to: 'usuarios#new'
  get 'usuarios/edit', to: 'usuarios#edit'
  get 'usuarios/show', to: 'usuarios#show'
  get 'usuarios/destroy', to: 'usuarios#destroy'
  get 'locals/new', to: 'locals#new'
  get 'locals/edit', to: 'locals#edit'
  get 'locals/show', to: 'locals#show'
  get 'locals/destroy', to: 'locals#destroy'
  get 'comunas/new', to: 'comunas#new'
  get 'comunas/edit', to: 'comunas#edit'
  get 'comunas/show', to: 'comunas#show'
  get 'comunas/destroy', to: 'comunas#destroy'
  get 'gustos/new', to: 'gustos#new'
  get 'gustos/edit', to: 'gustos#edit'
  get 'gustos/show', to: 'gustos#show'
  get 'gustos/destroy', to: 'gustos#destroy'
  get 'comentarios/new', to: 'comentarios#new'
  get 'comentarios/edit', to: 'comentarios#edit'
  get 'comentarios/show', to: 'comentarios#show'
  get 'comentarios/destroy', to: 'comentarios#destroy'
  post 'users/index', to: 'equals#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

is-up/app/models/estado.rb
class Estado < ApplicationRecord
end

is-up/app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estado_params
      params.require(:estado).permit(:liker, :liked, :festado)
    end
end

is-up/app/helpers/estados_helper.rb
module EstadosHelper
end

is-up/app/views/estados/_form.html.erb
<%= form_with(model: estado, local: true) do |form| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :liker %>
    <%= form.text_field :liker %>
  </div>

  <div class="field">
    <%= form.label :liked %>
    <%= form.text_field :liked %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.number_field :estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

is-up/app/views/estados/edit.html.erb
<h1>Editing Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

is-up/app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estados</h1>

<table>
  <thead>
    <tr>
      <th>Liker</th>
      <th>Liked</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.liker %></td>
        <td><%= estado.liked %></td>
        <td><%= estado.estado %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

is-up/app/views/estados/new.html.erb
<h1>New Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>

is-up/app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Liker:</strong>
  <%= @estado.liker %>
</p>

<p>
  <strong>Liked:</strong>
  <%= @estado.liked %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @estado.estado %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>