is-up/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :equals
  resources :estados
  get 'users/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'welcome#index'
  resources :comentarios
  resources :gustos
  resources :locals
  resources :comunas
  resources :usuarios
  resources :users
  get 'welcome/index'
  root 'welcome#index'
  get 'users/index2', to: 'users#index2'
  get 'welcome/index', to: 'welcome#index'
  get 'usuarios/new', to: 'usuarios#new'
  get 'usuarios/edit', to: 'usuarios#edit'
  get 'usuarios/show', to: 'usuarios#show'
  get 'usuarios/destroy', to: 'usuarios#destroy'
  get 'locals/new', to: 'locals#new'
  get 'locals/edit', to: 'locals#edit'
  get 'locals/show', to: 'locals#show'
  get 'locals/destroy', to: 'locals#destroy'
  get 'comunas/new', to: 'comunas#new'
  get 'comunas/edit', to: 'comunas#edit'
  get 'comunas/show', to: 'comunas#show'
  get 'comunas/destroy', to: 'comunas#destroy'
  get 'gustos/new', to: 'gustos#new'
  get 'gustos/edit', to: 'gustos#edit'
  get 'gustos/show', to: 'gustos#show'
  get 'gustos/destroy', to: 'gustos#destroy'
  get 'comentarios/new', to: 'comentarios#new'
  get 'comentarios/edit', to: 'comentarios#edit'
  get 'comentarios/show', to: 'comentarios#show'
  get 'comentarios/destroy', to: 'comentarios#destroy'
  post 'users/index', to: 'equals#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

is-up/app/models/usuario.rb
# frozen_string_literal: true

class Usuario < ApplicationRecord
end

is-up/app/controllers/usuarios_controller.rb
# frozen_string_literal: true

class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[show edit update destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show; end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit; end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def usuario_params
    params.require(:usuario).permit(:mail, :nombre, :descripcion, :edad, :imagen, :gustos, :telefono, :comuna)
  end
end

is-up/app/helpers/usuarios_helper.rb
# frozen_string_literal: true

module UsuariosHelper
end

is-up/app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.number_field :imagen %>
  </div>

  <div class="field">
    <%= form.label :gustos %>
    <%= form.number_field :gustos %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.number_field :telefono %>
  </div>

  <div class="field">
    <%= form.label :comuna %>
    <%= form.text_field :comuna %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

is-up/app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

is-up/app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Mail</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Edad</th>
      <th>Imagen</th>
      <th>Gustos</th>
      <th>Telefono</th>
      <th>Comuna</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.mail %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.descripcion %></td>
        <td><%= usuario.edad %></td>
        <td><%= usuario.imagen %></td>
        <td><%= usuario.gustos %></td>
        <td><%= usuario.telefono %></td>
        <td><%= usuario.comuna %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_usuario_path %>
<br>
<br>
<%= link_to 'Volver', controller:'welcome', action:'index' %>

is-up/app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

is-up/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mail:</strong>
  <%= @usuario.mail %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @usuario.descripcion %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @usuario.edad %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @usuario.imagen %>
</p>

<p>
  <strong>Gustos:</strong>
  <%= @usuario.gustos %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @usuario.telefono %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @usuario.comuna %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>