is-up/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :equals
  resources :estados
  get 'users/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'welcome#index'
  resources :comentarios
  resources :gustos
  resources :locals
  resources :comunas
  resources :usuarios
  resources :users
  get 'welcome/index'
  root 'welcome#index'
  get 'users/index2', to: 'users#index2'
  get 'welcome/index', to: 'welcome#index'
  get 'usuarios/new', to: 'usuarios#new'
  get 'usuarios/edit', to: 'usuarios#edit'
  get 'usuarios/show', to: 'usuarios#show'
  get 'usuarios/destroy', to: 'usuarios#destroy'
  get 'locals/new', to: 'locals#new'
  get 'locals/edit', to: 'locals#edit'
  get 'locals/show', to: 'locals#show'
  get 'locals/destroy', to: 'locals#destroy'
  get 'comunas/new', to: 'comunas#new'
  get 'comunas/edit', to: 'comunas#edit'
  get 'comunas/show', to: 'comunas#show'
  get 'comunas/destroy', to: 'comunas#destroy'
  get 'gustos/new', to: 'gustos#new'
  get 'gustos/edit', to: 'gustos#edit'
  get 'gustos/show', to: 'gustos#show'
  get 'gustos/destroy', to: 'gustos#destroy'
  get 'comentarios/new', to: 'comentarios#new'
  get 'comentarios/edit', to: 'comentarios#edit'
  get 'comentarios/show', to: 'comentarios#show'
  get 'comentarios/destroy', to: 'comentarios#destroy'
  post 'users/index', to: 'equals#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

is-up/app/models/local.rb
# frozen_string_literal: true

class Local < ApplicationRecord
end

is-up/app/controllers/locals_controller.rb
# frozen_string_literal: true

class LocalsController < ApplicationController
  before_action :set_local, only: %i[show edit update destroy]

  # GET /locals
  # GET /locals.json
  def index
    @locals = Local.all
  end

  # GET /locals/1
  # GET /locals/1.json
  def show; end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit; end

  # POST /locals
  # POST /locals.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local was successfully created.' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locals/1
  # PATCH/PUT /locals/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to @local, notice: 'Local was successfully updated.' }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1
  # DELETE /locals/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to locals_url, notice: 'Local was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_local
    @local = Local.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def local_params
    params.require(:local).permit(:nombre, :descripcion, :valoracion, :comentarios, :imagen)
  end
end

is-up/app/helpers/locals_helper.rb
# frozen_string_literal: true

module LocalsHelper
end

is-up/app/views/locals/_form.html.erb
<%= form_with(model: local, local: true) do |form| %>
  <% if local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :valoracion %>
    <%= form.text_field :valoracion %>
  </div>

  <div class="field">
    <%= form.label :comentarios %>
    <%= form.number_field :comentarios %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.number_field :imagen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

is-up/app/views/locals/edit.html.erb
<h1>Editing Local</h1>

<%= render 'form', local: @local %>

<%= link_to 'Show', @local %> |
<%= link_to 'Back', locals_path %>

is-up/app/views/locals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locales</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Valoracion</th>
      <th>Comentarios</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locals.each do |local| %>
      <tr>
        <td><%= local.nombre %></td>
        <td><%= local.descripcion %></td>
        <td><%= local.valoracion %></td>
        <td><%= local.comentarios %></td>
        <td><%= local.imagen %></td>
        <td><%= link_to 'Show', local %></td>
        <td><%= link_to 'Edit', edit_local_path(local) %></td>
        <td><%= link_to 'Destroy', local, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Local', new_local_path %>
<br>
<br>
<%= link_to 'Volver', controller:'welcome', action:'index' %>

is-up/app/views/locals/new.html.erb
<h1>New Local</h1>

<%= render 'form', local: @local %>

<%= link_to 'Back', locals_path %>

is-up/app/views/locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @local.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @local.descripcion %>
</p>

<p>
  <strong>Valoracion:</strong>
  <%= @local.valoracion %>
</p>

<p>
  <strong>Comentarios:</strong>
  <%= @local.comentarios %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @local.imagen %>
</p>

<%= link_to 'Edit', edit_local_path(@local) %> |
<%= link_to 'Back', locals_path %>