is-up/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :equals
  resources :estados
  get 'users/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'welcome#index'
  resources :comentarios
  resources :gustos
  resources :locals
  resources :comunas
  resources :usuarios
  resources :users
  get 'welcome/index'
  root 'welcome#index'
  get 'users/index2', to: 'users#index2'
  get 'welcome/index', to: 'welcome#index'
  get 'usuarios/new', to: 'usuarios#new'
  get 'usuarios/edit', to: 'usuarios#edit'
  get 'usuarios/show', to: 'usuarios#show'
  get 'usuarios/destroy', to: 'usuarios#destroy'
  get 'locals/new', to: 'locals#new'
  get 'locals/edit', to: 'locals#edit'
  get 'locals/show', to: 'locals#show'
  get 'locals/destroy', to: 'locals#destroy'
  get 'comunas/new', to: 'comunas#new'
  get 'comunas/edit', to: 'comunas#edit'
  get 'comunas/show', to: 'comunas#show'
  get 'comunas/destroy', to: 'comunas#destroy'
  get 'gustos/new', to: 'gustos#new'
  get 'gustos/edit', to: 'gustos#edit'
  get 'gustos/show', to: 'gustos#show'
  get 'gustos/destroy', to: 'gustos#destroy'
  get 'comentarios/new', to: 'comentarios#new'
  get 'comentarios/edit', to: 'comentarios#edit'
  get 'comentarios/show', to: 'comentarios#show'
  get 'comentarios/destroy', to: 'comentarios#destroy'
  post 'users/index', to: 'equals#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

is-up/app/models/comentario.rb
# frozen_string_literal: true

class Comentario < ApplicationRecord
end

is-up/app/controllers/comentarios_controller.rb
# frozen_string_literal: true

class ComentariosController < ApplicationController
  before_action :set_comentario, only: %i[show edit update destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show; end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit; end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comentario
    @comentario = Comentario.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comentario_params
    params.require(:comentario).permit(:local, :mailusuario, :fechahora, :descripcion, :puntaje)
  end
end

is-up/app/helpers/comentarios_helper.rb
# frozen_string_literal: true

module ComentariosHelper
end

is-up/app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local %>
  </div>

  <div class="field">
    <%= form.label :mailusuario %>
    <%= form.text_field :mailusuario %>
  </div>

  <div class="field">
    <%= form.label :fechahora %>
    <%= form.datetime_select :fechahora %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :puntaje %>
    <%= form.number_field :puntaje %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

is-up/app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

is-up/app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Local</th>
      <th>Mailusuario</th>
      <th>Fechahora</th>
      <th>Descripcion</th>
      <th>Puntaje</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.local %></td>
        <td><%= comentario.mailusuario %></td>
        <td><%= comentario.fechahora %></td>
        <td><%= comentario.descripcion %></td>
        <td><%= comentario.puntaje %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Comentario', new_comentario_path %>
<br>
<br>
<%= link_to 'Volver', controller:'welcome', action:'index' %>

is-up/app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

is-up/app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Local:</strong>
  <%= @comentario.local %>
</p>

<p>
  <strong>Mailusuario:</strong>
  <%= @comentario.mailusuario %>
</p>

<p>
  <strong>Fechahora:</strong>
  <%= @comentario.fechahora %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @comentario.descripcion %>
</p>

<p>
  <strong>Puntaje:</strong>
  <%= @comentario.puntaje %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>